#!/bin/bash

set -e

if [ ! -d ".venv" ]; then
    echo "############################################"
    echo "Creating virtualenv and installing packages"
    echo "############################################"
    ./install_deps.sh
fi

# shellcheck disable=SC1091
source .venv/bin/activate

torchrun --nproc_per_node 1 steve.py