#!/bin/bash

set -e

if [ ! -d ".venv" ]; then
    echo "############################################"
    echo "Creating virtualenv and installing packages"
    echo "############################################"
    python -m venv .venv
    # shellcheck disable=SC1091
    source .venv/bin/activate
    pip install -e ./llama_steve
    pip install -e ./llama

fi

# shellcheck disable=SC1091
source .venv/bin/activate

torchrun --nproc_per_node 1 llama_steve/llama_steve